### ISSUE TITLE
Semantic relevance about words visualized by attention

### ISSUE THREAD

**Issue by liaozeyi** [KillersDeath/SPWE#1]
老哥，请问下这个attention你是怎么判断哪两个词关联的呢？                       我是用bertviz tool可视化了一下，发现比如说绝对值三个字，我的那个模型里面，到12层反而注意力都分开了。。前面几层倒还是互相关联到了。

**Comment by liaozeyi** [comment]
https://www.jianshu.com/p/1e2a63cc9ba3

**Comment by Aurelius84** [comment]
我是把attention对应的权重拿出来，进行了可视化。如果你的attention的维度和词序列的维度是一样的话，也可以直接渲染。



> 我的那个模型里面，到12层反而注意力都分开了
attention值与词的对应关系是否一一对应呢？

**Comment by liaozeyi** [comment]
好的，明白明白，我想请问下你的模型输入的，比如说一个词组 “喜欢”，那他这个是你直接喜欢生成的向量，还是喜 欢 两个字的向量 合并生成自己的向量呢？

---Original---

**Comment by Aurelius84** [comment]
> 还是喜 欢 两个字的向量 合并生成自己的向量呢

我这里是「喜欢」对应的向量。你的是以「字」为单位进行的embedding吧？我这里是以「词」为单位的。

**Comment by liaozeyi** [comment]
嗯嗯，是的，我就是自己那个做的习题推荐的一个selfattention的可视化，可是那样一个字一个字的似乎关系挺不好看的。 但是我就是通过bert生成词的embedding的，那请问想你的词向量是怎么生成的呢？ 自己训练的模型吗？ 还是用bert呢



---Original---

**Comment by Aurelius84** [comment]
我是自己训练的，bert生成的词embedding一般还不错吧。是因为你的语料规模不大，还是训练的epoch不够？

上面你说前面几层「关联」效果还不错，到第十二层后就分开了。

+ 你是可以把每层的效果都看下，排除下网络的原因。
+ 你可以多观察几组样例，避免低频词效果的偏差

**Comment by liaozeyi** [comment]
嗯嗯 ，后面分开了我觉得可能是selfattention就是这样的？ 我看一篇论文说selfattention就是这样机制。
&nbsp;我主要是看到你那个情感分析的attention，我有一个比较不太明白的地方。 我做的可视化，他应该是一个词和别的词的attention注意力，请问你的那个直接可视化是那几个词组关于谁的attention呢？



---Original---

**Comment by Aurelius84** [comment]
> 请问你的那个直接可视化是那几个词组关于谁的attention呢？

我可视化的是「词性」计算出来的权重，用来加权「词」序列对应的语义feature.

**Comment by liaozeyi** [comment]
好的，了解了，谢谢老哥。&nbsp;



---Original---
